name: CI/CD Pipeline - Visioner-Control-SDLA

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Code
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        pip install pytest
        pytest tests/

    - name: Check TensorFlow/Model Load
      run: |
        python -c "import tensorflow as tf; print(tf.__version__)"
        python -c "from app.model_loader import load_model; load_model()"

    - name: Deploy to Raspberry Pi
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        source: "."
        target: ${{ secrets.PI_TARGET_DIR }}

    - name: Restart Service on Pi
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        script: |
          cd ${{ secrets.PI_TARGET_DIR }}
          ./restart.sh
